package com.eat.models.common.enums;

public enum ImageType {

    CATEGORY, PLACE_CATEGORY, FREE_PLACE_CATEGORY, PAID_PLACE_CATEGORY, PLACE_GALLERY, OFFER_TYPE, COLLECTION, USER_PROFILE,
    USER_BACKGROUND, PLACE_TYPE

}